### ISSUE TITLE
Multiple sendRawTransaction

### ISSUE THREAD

**Issue by SephirothLT** [O3Labs/O3Android#127]
Hi,I have met a question that I had send a nep-5 token's TNC  transaction that amount is 10654 in my app,but real amount transfered to target account is 21.47483647, Why?

**Comment by SephirothLT** [comment]
@apisit

**Comment by apisit** [comment]
you might have a very very old code. try using the latest one.

**Comment by SephirothLT** [comment]
I found  in sendNep5Transaction -->buildNEP5TransferScript  
![image](https://user-images.githubusercontent.com/20485889/40461318-59388d0a-5f3d-11e8-96ef-6591f16b0ef8.png)
Int  is not enough?

**Comment by apisit** [comment]
yep. it should be .toLong()
