### ISSUE TITLE
Login - Fall back screen when user cancels PIN entry

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#150]
To avoid users getting confused and logging out accidentally, we want to implement a fallback screen.

When the user hits cancel they will see the Please login screen.
![loginview](https://user-images.githubusercontent.com/16552874/41389385-8a97a5f4-6fcb-11e8-884c-7e371bd25f25.png)

If they Hit logout, they will receive a popup asking them if they are sure.
![loginview_areyousure](https://user-images.githubusercontent.com/16552874/41389386-8cc39dd8-6fcb-11e8-8dc5-abe5260ecc0a.png)

Note the "delete key and logout" forces the user to make the decision to delete the key from the device, hopefully reinforcing the seriousness of the action.

**Comment by saltyskip** [comment]
done, desig
