### ISSUE TITLE
News

### ISSUE THREAD

**Issue by saltyskip** [O3Labs/O3Android#16]
Add News feed. This could be in its own tab or below/ above the asset list in the portfolio page. On my device there is a lot of extra space below on that page. On smaller devices it might be tricky.

**Comment by saltyskip** [comment]
Replace the news icon with something more newsy. Right now it looks more like mailbox.

![image](https://user-images.githubusercontent.com/14796429/34278789-e1ed9f5a-e661-11e7-8d53-bab25e7850d0.png)


to somethhing like this

![image](https://user-images.githubusercontent.com/14796429/34278806-f29185ba-e661-11e7-90d7-7721dad82e2e.png)

Thoughts?

**Comment by apisit** [comment]
dooone
