### ISSUE TITLE
Address doesn't show up until after close and open app

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#163]
When I added an address via the "add this address to contacts" checkbox, it didn't show up in my address book (wallet screen tab) until I closed and opened the app. Then it was there. (Probably not a real big deal, just was worried it didn't work and would have to do it again later).

NB: I had already added the address before but did it again with a new name.

**Comment by saltyskip** [comment]
Ill add pull to refresh on that page

**Comment by saltyskip** [comment]
done
