### ISSUE TITLE
Exceeded amount not showing if token selected after amount entered

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#164]
One send/What Screen. Enter in an amount, and then select a token that has less than that amount.

It doesn't update the amount available to be red.

I am also thinking it's hard to see a bit, especially when there is only a single digit. 
Want to make ti stand out a little more. 

Maybe turn the big amount red? Or some extra text "Insufficient tokens" would work.
What do you think?

**Comment by saltyskip** [comment]
I think upping the balance text size in general is a good idea

**Comment by saltyskip** [comment]
done
