### ISSUE TITLE
Switch loading featured news from json to the API

### ISSUE THREAD

**Issue by apisit** [O3Labs/O3Android#169]
I thought it's already done but it looks like it still loads from JSON file

this api 
> https://platform.o3.network/api/v1/neo/news/featured

**Comment by saltyskip** [comment]
done in release 1.11

**Comment by saltyskip** [comment]
I plan release 1.11 on Monday, if it is more urgent let me know, and I can push out the hotfix

**Comment by apisit** [comment]
nah not urgent. I just put everything in json.  totally can wait. Thanks!
