### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by saltyskip** [O3Labs/O3Android#18]
Figure out how to organize image assets in best way. Vector files?

**Comment by apisit** [comment]
I use SVG for everything now. 
Export SVG from Sketch and import vector to the project.

<img width="216" alt="screen shot 2017-12-21 at 7 16 50 am" src="https://user-images.githubusercontent.com/1012916/34231341-026379c8-e61f-11e7-9027-45de69163274.png">

**Comment by saltyskip** [comment]
Ok Ill go and replace all the existing jpgs then

**Comment by apisit** [comment]
svg all the things
