### ISSUE TITLE
Scanner for add watch address adds NEO: in front of addresses.

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#184]
Goto settings, select add watch address, tap scan, then I scan an address from the desktop wallet and it grabs the address but has neo: in front of it. and it says it's invalid.

Deleting the neo: fixes the issue.

**Comment by saltyskip** [comment]
@fujita <- not sure where the URI is, but maybe it is preferred to have it as not a NEP 9 there. As the address could be scanned for another purpose as opposed to creating a send transaction

**Comment by creyeknife** [comment]
My thinking was in the future to have 2 options. One is simple My address, and the second would be to create a specific request.
It basically is that at the moment but could maybe be a little clearer to the user some how.

**Comment by saltyskip** [comment]
done
