### ISSUE TITLE
Scanner not adding amounts when using scanner

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#185]
After creating a NEP-9 on desktop wallet, I tried scanning in android app. 
It adds the address and selects the token, but doesn't add in the amount.

Also, if you don't have the token, it won't select it. 
I believe it should select it an tell you that you don't have any of this token. Thoughts?
Instead it auto selects neo, if the user doesnt notice and types in the amount and accidently sends 4000 NEO instead of ASA, we might have a problem lol.

**Comment by saltyskip** [comment]
done
