### ISSUE TITLE
Less that $0.01 portfolio UI

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#208]
In the portfolio, we have some items that do no have data and some that are > $0.01

I want to differentiate them by showing the difference at it to show we either don't know or its just really small.

I think we already had something but seems to have gone away since we introduced the pricing api from the server maybe?

Would something like this be possible? ONG just doesn't have any pricing data atm. but ACAT is so small that it just shows as > $0.00 Other coins like FTW which are airdropped and not listed have no ICO either so would show as unknown. 
I am even wondering if we should show the 0.00% for these as thats kind of useless data too. 

![pricedata](https://user-images.githubusercontent.com/16552874/45130624-6326e580-b1c4-11e8-8227-60bf67157e85.png)

**Comment by saltyskip** [comment]
done
