### ISSUE TITLE
Trading account list view

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#210]
The trading account list view doesn't update much. 

It seems you have to exit the app and go back into for it to update and sometimes it doesn't even then.

It's accurate if I try to withdraw etc even if it's not reflected correctly in the list.

Would be good to get this showing accurately before release, as I believe people will get pretty stressed out about it showing wrong values etc.

**Comment by saltyskip** [comment]
It will properly refresh on swipe down now
