### ISSUE TITLE
Updated layout for orders view.

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#212]
The current orders view is a bit squished and displays weird on my device. I assume this is probably a problem on other devices as well so I have make a quick update to it. 

![token detail_openorders](https://user-images.githubusercontent.com/16552874/45993639-c96b9d80-c0ca-11e8-802a-85cc07e2228b.png)

Moved the value to it's own line and stacked the token name icon on top.

Changed the arrow icon to single icon always pointing one way. This feels a bit weird still but I think it's easier than last one?

Also updated the price per token to read better. 0.223223 NEO = 1 CPX

**Comment by saltyskip** [comment]
Done
