### ISSUE TITLE
Account view Layout Updates

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#213]
Currently the account views is a bit much on the eyes I think.

![wallet_assets_wcontract](https://user-images.githubusercontent.com/16552874/45994360-392f5780-c0ce-11e8-88d2-3b479bb271eb.png)

I still want to keep the action bar up the top. 
I want to keep the scan option as I think it will be a powerful feature in the future, and easier to find the send and request without needing to think about which wallet etc. It's not really how people think when they want to send, so I want to try and avoid that, even if we have multiple wallets in the future. 

For the accounts, can we remove all the shadows etc? 
Also, I am thinking we should just show a main option for the account and then have ... for everything else they can do. Makes it a bit cleaner but will also allow for flexibility in the future if there are more options etc. 

Update the account names to be the same style as the 'Claim' title.

**Comment by creyeknife** [comment]
I have realized we wanted to add the scan button into the top bar, and remove the action bar itself. 

Updated designs here

![wallet_assets_wcontract](https://user-images.githubusercontent.com/16552874/46052435-68e76980-c179-11e8-838f-d6d75d02d226.png)

**Comment by saltyskip** [comment]
I think Deposit and Withdraw should both be visible from the account

**Comment by saltyskip** [comment]
Closing, any serious changes here should be after release of V1 

and should be thought about in the context of this discussion

https://community.o3.network/t/account-based-multi-wallet-architecture/1083/5
