### ISSUE TITLE
Marketplace / Switcheo Integration

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#217]
I am thinking to remove the Trade on Switcheo from the token details screen and have only 1 access point through the top of the marketplace as a featured dApp for the time being. 

So the only option from the Token details is to buy or sell through native.

The Switcheo button could be at the bottom of token details if we really wanted it there but we want to push people towards using our service more. 

Thoughts?

Also change the text button to a more graphical feature item

<img width="199" alt="screen shot 2018-09-25 at 4 08 50 pm" src="https://user-images.githubusercontent.com/16552874/45998282-528bd000-c0dd-11e8-9261-6c20d3b602e9.png">

**Comment by saltyskip** [comment]
Done with Dapp Store
