### ISSUE TITLE
Badge on the orders tab for open orders

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#230]
I think it would be really good to have a badge showing how many orders are open, on the top tab in the wallet view. 

I am a bit worried people will forget they have orders active.

It will also draw a bit more focus to the tab which otherwise might go un-noticed to some.

**Comment by saltyskip** [comment]
![image](https://user-images.githubusercontent.com/14796429/46394525-572b3680-c724-11e8-96ef-1e927489efe6.png)
