### ISSUE TITLE
Green button on failed popup is confusing.

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#236]
Thinking that we should change this button to the orange maybe? It's weird that it fails and the button is green, suggesting success. 

Guessing it might be hard to change just this popup and not the others. Maybe they can all be Orange instead?

![screenshot_20181003-120715](https://user-images.githubusercontent.com/16552874/46388065-1839b880-c705-11e8-9d7c-58f060a04920.png)

**Comment by creyeknife** [comment]
oh also , deposits are failing 😅 Not sure why

**Comment by saltyskip** [comment]
Will change to orange
