### ISSUE TITLE
Order filled states when placing an order

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#238]
We spoke about showing different states depending on how much of your order gets filled when it's submitted

I had these designs already but not sure how we wanna approach it yet. 

Thoughts?

<img width="1145" alt="screen shot 2018-10-03 at 2 43 42 pm" src="https://user-images.githubusercontent.com/16552874/46392112-0531e300-c71b-11e8-86d3-8f5f48046450.png">

**Comment by saltyskip** [comment]
We'll display simple percentage in V1, let's revisit this after native trading is released into the wild
