### ISSUE TITLE
Issue with trading account  displaying incorrectly

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#240]
I am getting this weird thing, part of the same problem I have been having where it shows +17 when there is actually nothing there.

Also, on a similar note, I think we should show that there is stuff in your trade account some how if it's all in orders. Switcheo shows as 0 but has a ( ! ) With a note saying it's 0 because it's currently in an order. Think we can do something similar some how?

![screenshot_20181003-151749](https://user-images.githubusercontent.com/16552874/46393352-cce0d380-c71f-11e8-8bcd-181e56936509.png)

**Comment by saltyskip** [comment]
done
