### ISSUE TITLE
Order submitted messages

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#243]
**0%**
“Order submitted. Check the status of your order under My O3 Wallet > Orders Tab.

**Partially filled.**
14% of your order instantly filled and has been deposited into your trading account! Check the status of remaining order under My O3 Wallet > Orders Tab.

**100%**
Your order has been instantly filled and deposited into your trading account! 🎉💃

**Comment by saltyskip** [comment]
done
