### ISSUE TITLE
New O3 Blue Update - #218FFF

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#249]
We have already added it to the text but still need to clean up a few icons etc to make sure it's all matching. 

Wallet screen:
Send/Request .  Withdraw/Deposit

Elements on the send flow

Are these able to be tinted or do we need new assets?
LMK

**Comment by saltyskip** [comment]
I think I'm good on everything except the APP icon

![image](https://user-images.githubusercontent.com/14796429/46987927-3a81fc00-d131-11e8-8f9b-4f13bca44281.png)

need these assets

![image](https://user-images.githubusercontent.com/14796429/46987936-4241a080-d131-11e8-9157-6bf49183c4d8.png)
The packground is just the png in the correct color

**Comment by creyeknife** [comment]
Ah yep, can you send me the dimensions required, I didn’t do the original one

**Comment by saltyskip** [comment]
Done
