### ISSUE TITLE
Activate Mutli-wallet > New encrypted key has wrong image in center

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#263]
When you activate multiwallet, enter a password and generate a new EPK, the icon in the middle of the QR is the O3 logo. 

Fix
For the sake of consistency across the apps, change the logo to the green key icon.

**Comment by creyeknife** [comment]
Another small change while you are on this view, can we raise the "Awesome! All done!" text up a few points and make it bold. Will add better layering to the view.

**Comment by saltyskip** [comment]
Text unfortunately barefly fits as is on smaller device. Will not do for now. Key has been updated
