### ISSUE TITLE
Extra options for Browser in dark mode is hard to read

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#271]
When tapping the ... button on the browser in dark mode, the text and icons are the lighter gray (how they should be) but the background doesn't change color to dark gray so it's hard to read. 
![screenshot_20181210-142355](https://user-images.githubusercontent.com/16552874/49712349-59ab8e80-fc87-11e8-9dd4-9031bc65c3e2.png)

Fix: change menu background to black.

**Comment by saltyskip** [comment]
done
