### ISSUE TITLE
Error is not user friendly 

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#276]
I am assuming this error is because I was trying to buy something under a certain threshold? I was only spending 50c 
![screenshot_20181226-182032](https://user-images.githubusercontent.com/16552874/50440796-1d408980-093b-11e9-9e9d-33102c98d1e1.png)

**Comment by creyeknife** [comment]
Ahh it seems to be something else, but the error itself is not very helpful for user, so would be good if we can put something there. Even if it's generic like "Something went wrong"

**Comment by saltyskip** [comment]
dixed
