### ISSUE TITLE
on-boarding - Short freeze when generating the encrypted key.

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#280]
When you hit Generate and it creates the new key, there is a freeze for a few seconds where the app feels it has locked up. There is no feedback on the button and I usually try and press it a few times to make sure something is happening. 

Could we swap the button for a loader for those few seconds? Or at least swap it for text saying generating key, if performance is an issue here.

**Comment by saltyskip** [comment]
Done
