### ISSUE TITLE
On-boarding - Login with Key page fixes

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/O3Android#283]
Add animation of key to private key entry page. 
an_enter_key.json can be found here: https://drive.google.com/open?id=1OKPmEC0aGv1YJvADgvHIa5k_AKNQFPtW

Reduce size of text box to be the same as the password entry ones on the new wallet view.

**Comment by saltyskip** [comment]
I make the textbox bigger because it is required to be that size to fit the private key no matter what type. It is always two lines. Updated animation
