### ISSUE TITLE
Add transaction result info returned from SendV2 activity

### ISSUE THREAD

**Issue by mettizik** [O3Labs/O3Android#303]
I have an application which requires interactions with wallet for in-app purchases. 
But it seems that SendV2 activity does not return any information about what the result of transaction actually was.
What we are looking for, is information about sender, receiver, amount sent, in which tokens, overall status like success / fail or so.

Is there any way to get this info now, or can it be added in nearest feature?

**Comment by mokychandrey** [comment]
@saltyskip , can you take a look here?

**Comment by saltyskip** [comment]
Hi can you clarify the question. My understanding is that you have another Android app and are attempting to open SendV2Activity through an intent if the user has O3 installed in order to process a payment? Once the payment succeeds there should be some sort of broadcast back to your app to notify success. Is this correct?

Do you have a link to the app if thats the case, it would make it easier to visualize this scenario?

**Comment by mokychandrey** [comment]
@saltyskip , Hi! I apologize for long reply:

> My understanding is that you have another Android app and are attempting to open SendV2Activity through an intent if the user has O3 installed in order to process a payment?

yes, use case is exactly one you described.

> Once the payment succeeds there should be some sort of broadcast back to your app to notify success.

actually we are just calling [startActivityForResult](https://developer.android.com/reference/android/app/Activity.html#startActivityForResult(android.content.Intent,%20int)) and then receiving the result, which can be set, in wallet by [setResult](https://developer.android.com/reference/android/app/Activity.html#setResult(int,%2520android.content.Intent)) and it would be the best for us.

> Do you have a link to the app if thats the case, it would make it easier to visualize this scenario?

Unfortunately - no, it is under development, and is not available in source code form yet.

What we need now is just a result of activity, which we could use to determine, that correct amount of correct tokens was sent to correct address and transaction succeeded.

**Comment by Alexandr1992** [comment]
@saltyskip, Hi! Do you have any updates on this issue?

**Comment by saltyskip** [comment]
Hi its not really on my roadmap for the time being as there are other improvements I am working on. My reccomendations at this time would be either to use the DAPI standard which allows access to send and returns transaction ids via a webview.

Or if you would like to clone the project and make an update that supports this functionality I would happily accept it

**Comment by mokychandrey** [comment]
@saltyskip , thanks for your time here. 
Can you, please, clarify the following - if would fork and PR into your project the solution, will it be possible to release an update of the application to Play Market, with this feature by the end of May?

**Comment by saltyskip** [comment]
Depends on what the PR looks like...we generally release a new version every two weeks. After merge I would expect two weeks after that time

**Comment by mokychandrey** [comment]
Sounds great, thanks

**Comment by saltyskip** [comment]
close

https://github.com/O3Labs/O3Android/pull/308
