### ISSUE TITLE
Gradle refresh failed

### ISSUE THREAD

**Issue by SephirothLT** [O3Labs/O3Android#63]
This is log info:Error:前言中不允许有内容。
I can not compile the project and modules,My AS is 3.0.1 ,Gradle version is 4.1

**Comment by saltyskip** [comment]
Likely Android Manifest is encrypted as it contains some semi sensitive information. I can put up a useable manifest tomorrow

**Comment by SephirothLT** [comment]
@saltyskip  Thanks

**Comment by SephirothLT** [comment]
@saltyskip here is my email ,sephirothltcl@gmail.com,tks
