### ISSUE TITLE
Error:Content is not allowed in prolog.

### ISSUE THREAD

**Issue by imaNNeoFighT** [O3Labs/O3Android#91]
Hi, check this file : 
O3Android/app/src/main/AndroidManifest.xml
(it is unusual at all, there is some raw and binary texts)

**Comment by saltyskip** [comment]
I encrypt the manifest. Can you send me an email at hello@o3.network, if you're looking to build from source/contribute

**Comment by imaNNeoFighT** [comment]
Sure, i will.
