### ISSUE TITLE
How can I get txid when I transfer tokens? &&  Conflict about install

### ISSUE THREAD

**Issue by SephirothLT** [O3Labs/O3Android#95]
How can I get txid when I transfer tokens or NEO/GAS?    Just received the   boolean result of transfer for now...   
Another question:  Could  you  give me some advice  about  how to resolve the conflict of "the library of neoutils“   when I  install my testApp that use the same library(neoutils) as O3 ?
Thanks!!!

**Comment by saltyskip** [comment]
Answered in Discord
