### ISSUE TITLE
Encrypt password and privateKey

### ISSUE THREAD

**Issue by SephirothLT** [O3Labs/O3Android#96]
In O3-iOS  library  have a method -`public func exportEncryptedKey(with passphrase: String) -> String {
        return NEP2.encryptKey(self.privateKey.bytes, passphrase: passphrase, address: self.address)
    }`
the android  have the same method?
Thanks!!!

**Comment by SephirothLT** [comment]
@apisit  Could you give me some advice?Thanks!!!

**Comment by saltyskip** [comment]
No, it doesnt
